### ISSUE TITLE
crash and exit due to longclick

### ISSUE THREAD

**Issue by jyjsunny** [segler-alex/RadioDroid#1099]
### Description

App crashes and quits due to long click on a specific position

### There is a video:

https://user-images.githubusercontent.com/92309998/169691538-e47d4486-868d-4322-826a-0de472cf44b9.mov

### Steps to reproduce

1. Open history screen
2. Click to display the keywords of the current radio
3. Click on the middle blank part of multiple search terms for a long time. **(long click)**
6. crash and exit

### Information

Android version: Android 8
Device: Google Pixel XL
App Version: 0.84

### Stack Trace

: java.lang.NullPointerException: Attempt to invoke interface method 'void net.programmierecke.radiodroid2.interfaces.IFragmentSearchable.Search(net.programmierecke.radiodroid2.station.StationsFilter$SearchStyle, java.lang.String)' on a null object reference
: 	at net.programmierecke.radiodroid2.FragmentTabs.Search(FragmentTabs.java:184)
: 	at net.programmierecke.radiodroid2.ActivityMain.Search(ActivityMain.java:897)
: 	at net.programmierecke.radiodroid2.ActivityMain.handleIntent(ActivityMain.java:518)
: 	at net.programmierecke.radiodroid2.ActivityMain.onResume(ActivityMain.java:544)
: 	at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1354)
: 	at android.app.Activity.performResume(Activity.java:7079)
: 	at android.app.ActivityThread.performNewIntents(ActivityThread.java:2985)
: 	at android.app.ActivityThread.handleNewIntent(ActivityThread.java:2999)
: 	at android.app.ActivityThread.-wrap14(Unknown Source:0)
: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1672)
: 	at android.os.Handler.dispatchMessage(Handler.java:105)
: 	at android.os.Looper.loop(Looper.java:164)
: 	at android.app.ActivityThread.main(ActivityThread.java:6541)
: 	at java.lang.reflect.Method.invoke(Native Method)
: 	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)

**Comment by jyjsunny** [comment]
@huftis Hello, Could I ask about the current status of this issue?

Looking forward to your reply!

**Comment by jyjsunny** [comment]
@huftis @segler-alex @rmtsrc @andrewshadura Hello, Could I ask about the current status of this issue?

Looking forward to your reply!
