### ISSUE TITLE
Recording fails if the "Music" directory doesn't exist

### ISSUE THREAD

**Issue by celsoazevedo** [segler-alex/RadioDroid#360]
I noticed that the recording feature doesn't work if the Music folder doesn't exist. If I create this folder, recording works as expected.

```
E/Recordings( 4762): could not create dir:/storage/emulated/0/Music/Recordings
W/System.err( 4762): java.io.FileNotFoundException: /storage/emulated/0/Music/Recordings/file.mp3 (No such file or directory)
```

Most people don't delete their default folders, but I did it when doing a "spring clean up". My suggestion would be for RadioDroid to automatically create this folder or at least inform the user why recording doesn't work.

**Comment by uzen** [comment]
Lineage os 14.1 (Android 7.1.2)



 `E/ActivityManager(583): applyOptionsLocked: Unknown animationType=0
 E/AndroidRuntime(29997): FATAL EXCEPTION: main
 E/AndroidRuntime(29997): Process: net.programmierecke.radiodroid2, PID: 29997
 E/AndroidRuntime(29997): android.os.FileUriExposedException: file:///storage/emulated/0/Music/Recordings/Radio_Hauraki_Radio_Hauraki_The_Station_for_Great_New_Zealanders_2018-09-25.mp3 exposed beyond app through Intent.getData()
 E/AndroidRuntime(29997): 	at android.os.StrictMode.onFileUriExposed(StrictMode.java:1796)
 E/AndroidRuntime(29997): 	at android.net.Uri.checkFileUriExposed(Uri.java:2354)
 E/AndroidRuntime(29997): 	at android.content.Intent.prepareToLeaveProcess(Intent.java:8981)
 E/AndroidRuntime(29997): 	at android.content.Intent.prepareToLeaveProcess(Intent.java:8942)
 E/AndroidRuntime(29997): 	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1519)
 E/AndroidRuntime(29997): 	at android.app.Activity.startActivityForResult(Activity.java:4229)
 E/AndroidRuntime(29997): 	at android.support.v4.app.BaseFragmentActivityApi16.startActivityForResult(BaseFragmentActivityApi16.java:54)
 E/AndroidRuntime(29997): 	at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:67)
 E/AndroidRuntime(29997): 	at android.support.v4.app.ActivityCompat.startActivityForResult(ActivityCompat.java:152)
 E/AndroidRuntime(29997): 	at android.support.v4.app.FragmentActivity.startActivityFromFragment(FragmentActivity.java:793)
 E/AndroidRuntime(29997): 	at android.support.v4.app.FragmentActivity$HostCallbacks.onStartActivityFromFragment(FragmentActivity.java:907)
 E/AndroidRuntime(29997): 	at android.support.v4.app.Fragment.startActivity(Fragment.java:1009)
 E/AndroidRuntime(29997): 	at android.support.v4.app.Fragment.startActivity(Fragment.java:998)
 E/AndroidRuntime(29997): 	at net.programmierecke.radiodroid2.FragmentRecordings.ClickOnItem(FragmentRecordings.java:35)
 E/AndroidRuntime(29997): 	at net.programmierecke.radiodroid2.FragmentRecordings$1.onItemClick(FragmentRecordings.java:53)
 E/AndroidRuntime(29997): 	at android.widget.AdapterView.performItemClick(AdapterView.java:310)
 E/AndroidRuntime(29997): 	at android.widget.AbsListView.performItemClick(AbsListView.java:1164)
 E/AndroidRuntime(29997): 	at android.widget.AbsListView$PerformClick.run(AbsListView.java:3139)
 E/AndroidRuntime(29997): 	at android.widget.AbsListView$3.run(AbsListView.java:4054)
 E/AndroidRuntime(29997): 	at android.os.Handler.handleCallback(Handler.java:751)
 E/AndroidRuntime(29997): 	at android.os.Handler.dispatchMessage(Handler.java:95)
 E/AndroidRuntime(29997): 	at android.os.Looper.loop(Looper.java:154)
 E/AndroidRuntime(29997): 	at android.app.ActivityThread.main(ActivityThread.java:6186)
 E/AndroidRuntime(29997): 	at java.lang.reflect.Method.invoke(Native Method)
 E/AndroidRuntime(29997): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
 E/AndroidRuntime(29997): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)`

**Comment by werman** [comment]
Sorry that none replied to the issue, I'll look into how to improve notifications when something going wrong with records.

 @uzen I believe you have another issue. Since RadioDroid just dumps stream output while recording the resulting file may not be liked by some players, at this moment I don't see a good solution but I didn't look too much into it. 
If RadioDroid crashes when opening the record from it - that's an issue and I'll try to fix it.

**Comment by morckx** [comment]
Fixed by #472
