### ISSUE TITLE
App crashes when clicking on a recording

### ISSUE THREAD

**Issue by orschiro** [segler-alex/RadioDroid#421]
Hi all, 

Every time I click on a recording to play it, the app crashes. 

I sent my feedback to you.

Is there anything else I can do to help?

**Comment by werman** [comment]
Hi,

What version of RadioDroid do you have?
What version of Android?
Does this recording exist on disk?

Thanks!

**Comment by orschiro** [comment]
Hi @werman,

- RadioDroid 0.66
- Android 7.1.2
- Yes, it does exist. I was able to play it using VLC

Thanks!

**Comment by werman** [comment]
Could you get stack trace from logcat?

**Comment by orschiro** [comment]
Sure, can you tell me how?

--
https://orzanna.de

**Comment by werman** [comment]
Assuming you have adb installed, connect the device, execute  ```adb logcat``` in terminal - it will print a lot of logs, make radiodroid crash and copy appeared logs with crash

**Comment by orschiro** [comment]
Thanks Danil.

I am going to try to get that information for you in the coming days.

At the moment, my phone is saying "USB debugging connected" (so ADB seems
to be working and is enabled under developer options) but my Linux laptop
just says:

[orschiro@x230 ~]$ adb logcat
- waiting for device -


--
https://orzanna.de

**Comment by werman** [comment]
ADB is a strange beast, the standard magic moves are:

- disconnect phone
- `adb kill-server`
- `adb start-server`
- reconnect phone

or

- `adb kill-server`
- `adb devices` (should show your connected phone)

or

Sometimes something going wrong with debugging authorization and you need more advanced [magic moves](https://stackoverflow.com/a/30565982).

Also you can look into dmesg and see if phone even recognized, something like:

```
 usb 5-2.4: new high-speed USB device number 4 using xhci_hcd
 usb 5-2.4: New USB device found, idVendor=18d1, idProduct=4ee7, bcdDevice= 2.32
 usb 5-2.4: New USB device strings: Mfr=1, Product=2, SerialNumber=3
 usb 5-2.4: Product: Nexus 5
```

**Comment by orschiro** [comment]
Hmm. I tried all recommended steps but it didn't work.

Will report back once I have found a solution!

Maybe someone else can jump in with similar issues and can provide the
debugging output?

--
https://orzanna.de

**Comment by iheinze** [comment]
I installed the App today and tested it. I have the same problem. RadioDroid version 0.66. Android version 8.1.0. It is not a big issue for me because I do not intend to use this feature. Anyway, here is what happened in my case:

`03-10 18:11:30.617 10225 21510 21510 D AndroidRuntime: Shutting down VM
03-10 18:11:30.621 10225 21510 21510 E AndroidRuntime: FATAL EXCEPTION: main
03-10 18:11:30.621 10225 21510 21510 E AndroidRuntime: Process: net.programmierecke.radiodroid2, PID: 21510
03-10 18:11:30.621 10225 21510 21510 E AndroidRuntime: android.os.FileUriExposedException: file:///storage/emulated/0/Music/Recordings/2ROCK_Stevie_Ray_Vaughan_Double_Trouble_Voodoo_Child_Slight_Return_2019-03-10_18-11.mp3 exposed beyond app through Intent.getData()
03-10 18:11:30.621 10225 21510 21510 E AndroidRuntime: 	at android.os.StrictMode.onFileUriExposed(StrictMode.java:1960)
03-10 18:11:30.621 10225 21510 21510 E AndroidRuntime: 	at android.net.Uri.checkFileUriExposed(Uri.java:2356)
03-10 18:11:30.621 10225 21510 21510 E AndroidRuntime: 	at android.content.Intent.prepareToLeaveProcess(Intent.java:10622)
03-10 18:11:30.621 10225 21510 21510 E AndroidRuntime: 	at android.content.Intent.prepareToLeaveProcess(Intent.java:10576)
03-10 18:11:30.621 10225 21510 21510 E AndroidRuntime: 	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1617)
03-10 18:11:30.621 10225 21510 21510 E AndroidRuntime: 	at android.app.Activity.startActivityForResult(Activity.java:4621)
03-10 18:11:30.621 10225 21510 21510 E AndroidRuntime: 	at android.support.v4.app.BaseFragmentActivityApi16.startActivityForResult(BaseFragmentActivityApi16.java:54)
03-10 18:11:30.621 10225 21510 21510 E AndroidRuntime: 	at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:67)
03-10 18:11:30.621 10225 21510 21510 E AndroidRuntime: 	at android.support.v4.app.ActivityCompat.startActivityForResult(ActivityCompat.java:152)
03-10 18:11:30.621 10225 21510 21510 E AndroidRuntime: 	at android.support.v4.app.FragmentActivity.startActivityFromFragment(FragmentActivity.java:793)
03-10 18:11:30.621 10225 21510 21510 E AndroidRuntime: 	at android.support.v4.app.FragmentActivity$HostCallbacks.onStartActivityFromFragment(FragmentActivity.java:907)
03-10 18:11:30.621 10225 21510 21510 E AndroidRuntime: 	at android.support.v4.app.Fragment.startActivity(Fragment.java:1009)
03-10 18:11:30.621 10225 21510 21510 E AndroidRuntime: 	at android.support.v4.app.Fragment.startActivity(Fragment.java:998)
03-10 18:11:30.621 10225 21510 21510 E AndroidRuntime: 	at net.programmierecke.radiodroid2.FragmentRecordings.ClickOnItem(FragmentRecordings.java:35)
03-10 18:11:30.621 10225 21510 21510 E AndroidRuntime: 	at net.programmierecke.radiodroid2.FragmentRecordings$1.onItemClick(FragmentRecordings.java:53)
03-10 18:11:30.621 10225 21510 21510 E AndroidRuntime: 	at android.widget.AdapterView.performItemClick(AdapterView.java:350)
03-10 18:11:30.621 10225 21510 21510 E AndroidRuntime: 	at android.widget.AbsListView.performItemClick(AbsListView.java:1674)
03-10 18:11:30.621 10225 21510 21510 E AndroidRuntime: 	at android.widget.AbsListView$PerformClick.run(AbsListView.java:4085)
03-10 18:11:30.621 10225 21510 21510 E AndroidRuntime: 	at android.widget.AbsListView$10.run(AbsListView.java:6573)
03-10 18:11:30.621 10225 21510 21510 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:790)
03-10 18:11:30.621 10225 21510 21510 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
03-10 18:11:30.621 10225 21510 21510 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:164)
03-10 18:11:30.621 10225 21510 21510 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7000)
03-10 18:11:30.621 10225 21510 21510 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
03-10 18:11:30.621 10225 21510 21510 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:441)
03-10 18:11:30.621 10225 21510 21510 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1408)`

**Comment by werman** [comment]
Huh, thanks for posting the exception, now we know where to look!
