### ISSUE TITLE
[bug] press recordings and then press "prev" button lead to fatal crash

### ISSUE THREAD

**Issue by tingsu** [segler-alex/RadioDroid#574]
- I have searched the history issue list, and have not found any similar issues. 

- The bug was found in the latest code commit (``RadioDroid-free-debug-DEV-0.79-da50202.apk``). It was reproduciable on both a Google Plxel 3 (Android 9.0) and an Android emulator 6.0 device

- Reproducing video

   ![20191013_141025](https://user-images.githubusercontent.com/3156978/66715409-59a67e80-edc3-11e9-8c01-769f32c12f67.gif)

- Crash stack

```
 FATAL EXCEPTION: main
 Process: net.programmierecke.radiodroid2, PID: 9113
 java.lang.NullPointerException: Attempt to read from field 'java.lang.String net.programmierecke.radiodroid2.station.DataRadioStation.StationUuid' on a null object reference
 	at net.programmierecke.radiodroid2.service.PlayerService.previous(PlayerService.java:495)
 	at net.programmierecke.radiodroid2.service.PlayerService$1.SkipToPrevious(PlayerService.java:139)
 	at net.programmierecke.radiodroid2.service.PlayerServiceUtil.skipToPrevious(PlayerServiceUtil.java:139)
 	at net.programmierecke.radiodroid2.FragmentPlayerFull.lambda$onActivityCreated$2(FragmentPlayerFull.java:318)
 	at net.programmierecke.radiodroid2.-$$Lambda$FragmentPlayerFull$YH-rncIxXkNbRPY-NjHE45Qrhl4.onClick(lambda)
 	at android.view.View.performClick(View.java:5198)
 	at android.view.View$PerformClick.run(View.java:21147)
 	at android.os.Handler.handleCallback(Handler.java:739)
 	at android.os.Handler.dispatchMessage(Handler.java:95)
 	at android.os.Looper.loop(Looper.java:148)
 	at android.app.ActivityThread.main(ActivityThread.java:5417)
 	at java.lang.reflect.Method.invoke(Native Method)
 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
Force finishing activity net.programmierecke.radiodroid2/.ActivityMain
```

**Comment by tingsu** [comment]
Thanks for your quick fix!
