### ISSUE TITLE
fatal crash when toggle views under Favorites

### ISSUE THREAD

**Issue by tingsu** [segler-alex/RadioDroid#580]
This issue was encountered in the latest code commit version (version 0.79, ``git a214abe``). But I forget to capture the whole bug-triggering event sequence.  I attached the stack trace here. Hope it is useful to localize the culprit of the issue.  Let me know if you need more info.

- the stack strace

```
 FATAL EXCEPTION: main
 Process: net.programmierecke.radiodroid2, PID: 32210
 java.lang.RuntimeException: Unable to start activity ComponentInfo{net.programmierecke.radiodroid2/net.programmierecke.radiodroid2.ActivityMain}: java.lang.NullPointerException: Attempt to invoke virtual method 'java.util.List androidx.fragment.app.FragmentManager.getFragments()' on a null object reference
 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2416)
 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
 	at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:4077)
 	at android.app.ActivityThread.-wrap15(ActivityThread.java)
 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1350)
 	at android.os.Handler.dispatchMessage(Handler.java:102)
 	at android.os.Looper.loop(Looper.java:148)
 	at android.app.ActivityThread.main(ActivityThread.java:5417)
 	at java.lang.reflect.Method.invoke(Native Method)
 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
 Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.util.List androidx.fragment.app.FragmentManager.getFragments()' on a null object reference
 	at net.programmierecke.radiodroid2.ActivityMain.Search(ActivityMain.java:798)
 	at net.programmierecke.radiodroid2.ActivityMain.onNewIntent(ActivityMain.java:432)
 	at net.programmierecke.radiodroid2.ActivityMain.onCreate(ActivityMain.java:127)
 	at android.app.Activity.performCreate(Activity.java:6237)
 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107)
 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2369)
 	... 10 more
Force finishing activity net.programmierecke.radiodroid2/.ActivityMain
```

**Comment by tingsu** [comment]
Any update for this issue? I encounter this issue one time.

**Comment by tingsu** [comment]
Sorry, I accidently click on the ``close issue`` button. I encounter this issue one time.

**Comment by werman** [comment]
Did you search clicked on station's tags?

The path to the crash involves clicking tags. I'll fix it.

**Comment by tingsu** [comment]
I cannot remeber very clearly about the steps. But the trace is short I remember. I tried hard to reproduce this issue, but unfortunately fail to provide you a good test.

**Comment by werman** [comment]
Already reproduced:
1) Click on station's tag
2) Go to "Favorites"
3) Click leftmost item in the top bar

**Comment by tingsu** [comment]
Good catch!

**Comment by tingsu** [comment]
@werman Can I know wa this issue fixed?

**Comment by werman** [comment]
@tingsu No it hasn't been fixed yet.

**Comment by tingsu** [comment]
Thanks for your quick reply to let me know the status. Also appreciate your efforts to maintain this nice app :) Waiting ...

**Comment by segler-alex** [comment]
could you retry with current master branch?

**Comment by tingsu** [comment]
I would like to help. Can you offer an compiled debug apk for me to test? Thanks.

**Comment by segler-alex** [comment]
thank you! the most current build is
[RadioDroid-play-debug-DEV-0.79-281fd1b.zip](https://github.com/segler-alex/RadioDroid/files/4119784/RadioDroid-play-debug-DEV-0.79-281fd1b.zip)

**Comment by oraluben** [comment]
> [RadioDroid-play-debug-DEV-0.79-281fd1b.zip](https://github.com/segler-alex/RadioDroid/files/4119784/RadioDroid-play-debug-DEV-0.79-281fd1b.zip)

Hi Alex, I've tested this version and looks like the issue has been fixed!
While testing this issue I found another crash likely related to my low-speed network.

**Comment by segler-alex** [comment]
i could not reproduce this problem, but i think i found the problem. please try again with the new version
[RadioDroid-play-debug-DEV-0.79-a7f6c4a.zip](https://github.com/segler-alex/RadioDroid/files/4130051/RadioDroid-play-debug-DEV-0.79-a7f6c4a.zip)

**Comment by oraluben** [comment]
It's fixed, thanks!
