### ISSUE TITLE
RadioDroid start at boot

### ISSUE THREAD

**Issue by cortomalese** [segler-alex/RadioDroid#725]
Hi, since last update (0.80) RadioDroid seems to start at boot time. I see a notification I didn't see before. How can I stop this please?
My phone is Fairphone 2, under LineageOS 16.0.
Thanks for your job !
Corto

**Comment by werman** [comment]
Would be fixed in the next 0.81 release (soon). There were a huge amount of changes in 0.80 and some issues with notifications slipped in, sorry.

**Comment by cortomalese** [comment]
Thank you for your answer!

**Comment by morckx** [comment]
@werman : I don't think that this one is already fixed with the current PRs. `onStartCommand` is called on boot completed and a notification is opened. Some measures that would fix the problem are: let `onStartCommand` check if `action` is null and/or let `BootReceiver`  call `PlayerServiceUtil.shutdownService()`  OR move the `BootReceiver` to `PlayerService` and handle everything there.  However, I can't overlook the respective side effects without research and don't know what option is preferable.

**Comment by werman** [comment]
Did you observe it being called? Because I'm not sure why it could be called now.

**Comment by werman** [comment]
There is no notification after restart in emulator.

**Comment by morckx** [comment]
Yes, there is a notification opened (and not closed) on boot on my Android 10.

**Comment by morckx** [comment]
Calling `PlayerServiceUtil.shutdownService()` from `BootReceiver` is no good idea. 
Checking if `action` is `null` in `onStartCommand` seems to work, but I don't know if only the notfication should be skipped or if it should return immediately and what the side effects would be.

**Comment by werman** [comment]
Sorry, I'm confused, I rebooted emulator api 28, reboot my phone with Android 9, there is no notification. And I don't see how it can be created. Are you sure you are running latest master? I know it's a stupid question but I have to ask.

**Comment by morckx** [comment]
Yes,  I'm on latest master and I have this problem since a while.

**Comment by morckx** [comment]
```
showNotification = action != null && intent.getBooleanExtra(PLAYER_SERVICE_NO_NOTIFICATION_EXTRA, false);
```
in onStartCommand seems to resolve this issue, but are there also situations where we want a notification when action is null or do we want return here immediately when action is null?

**Comment by werman** [comment]
I want to try understand  why on earth `onStartCommand` is even called. Do I need to do anything special? I've install RadioDroid, played a station, added alarm, restarted phone, and got no notification. Now tested on Android 10. 

> in onStartCommand seems to resolve this issue, but are there also situations where we want a notification when action is null or do we want return here immediately when action is null?

I don't know when our service could be started without intent, either we start service or media session, both pass intent. However even in such case we must show notification since Android O, there is a comment in that part of code about this (but we can immediately stop it).

**Comment by morckx** [comment]
> I want to try to understand why on earth `onStartCommand` is even called. Do I need to do anything special? I've install RadioDroid, played a station, added alarm, restarted phone, and got no notification. Now tested on Android 10.

I also have no idea and was wondering why this happens. However I do have this since before 107a00c9f7b0af0283982f32728dd8bdc2aca3a7 . Before that it was even more annoying because RadioDroid crashed on boot :)

> > in onStartCommand seems to resolve this issue, but are there also situations where we want a notification when action is null or do we want return here immediately when action is null?
> 
> I don't know when our service could be started without intent, either we start service or media session, both pass intent. However even in such case we must show notification since Android O, there is a comment in that part of code about this (but we can immediately stop it).

Yes, that's why I thought that just omitting the notification is not safe.

I don't have much more time today, but can test whatever you suggest.

**Comment by werman** [comment]
I'll make a fix tomorrow. But this is utter madness, who start the service...

**Comment by morckx** [comment]
> I'll make a fix tomorrow. But this is utter madness, who start the service...

Absolutely. I even let it log a stack trace :)

**Comment by morckx** [comment]
Yes, just omitting the notification works only in 4 of 5 cases:
```
2020-02-26 22:44:19.134 2439-2439/net.programmierecke.radiodroid2 E/AndroidRuntime: FATAL EXCEPTION: main
    Process: net.programmierecke.radiodroid2, PID: 2439
    java.lang.RuntimeException: Unable to start service net.programmierecke.radiodroid2.service.PlayerService@aba220d with Intent { cmp=net.programmierecke.radiodroid2/.service.PlayerService }: java.lang.IllegalStateException: Not allowed to start service Intent { cmp=net.programmierecke.radiodroid2/.service.PlayerService (has extras) }: app is in background uid UidRecord{8c44874 u0a330 SVC  idle change:uncached procs:1 seq(0,0,0)}
        at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:4105)
        at android.app.ActivityThread.access$1800(ActivityThread.java:219)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1891)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
     Caused by: java.lang.IllegalStateException: Not allowed to start service Intent { cmp=net.programmierecke.radiodroid2/.service.PlayerService (has extras) }: app is in background uid UidRecord{8c44874 u0a330 SVC  idle change:uncached procs:1 seq(0,0,0)}
        at android.app.ContextImpl.startServiceCommon(ContextImpl.java:1616)
        at android.app.ContextImpl.startService(ContextImpl.java:1571)
        at android.content.ContextWrapper.startService(ContextWrapper.java:669)
        at net.programmierecke.radiodroid2.service.PlayerServiceUtil.bind(PlayerServiceUtil.java:47)
        at net.programmierecke.radiodroid2.service.PlayerService.onStartCommand(PlayerService.java:501)
        at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:4087)
        at android.app.ActivityThread.access$1800(ActivityThread.java:219) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1891) 
        at android.os.Handler.dispatchMessage(Handler.java:107) 
        at android.os.Looper.loop(Looper.java:214) 
        at android.app.ActivityThread.main(ActivityThread.java:7356) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930) 
2020-02-26 22:44:19.138 2439-2439/net.programmierecke.radiodroid2 I/Process: Sending signal. PID: 2439 SIG: 9
```

**Comment by werman** [comment]
Could you filter adb logs to see all mentions of intent and devise who is sending it?

**Comment by morckx** [comment]
:man_facepalming: It's of course startet from `RadioDroidBrowserService` as I've already said here:

> I also have no idea and was wondering why this happens. However I do have this since before [107a00c](https://github.com/segler-alex/RadioDroid/commit/107a00c9f7b0af0283982f32728dd8bdc2aca3a7) . Before that it was even more annoying because RadioDroid crashed on boot :)

And as I've said, before that commit it couldn't start  `RadioBrowserService` and just crashed. I'll better get some sleep...

**Comment by werman** [comment]
`RadioDroidBrowserService`, yeah... Thanks. We can just disable it for now since Android Auto is not enabled yet.
