### ISSUE TITLE
Fatal crash when saving favorites at first time 

### ISSUE THREAD

**Issue by tingsu** [segler-alex/RadioDroid#778]
This crash issue was found in the latest released version (0.82). It was reproduciable on a Google Pixel 3 phone (Android 9.0) and Android emulator 6.0. I have searched the issue history, and have not found similar issues.

Reproducing video:

![20200330_102403](https://user-images.githubusercontent.com/3156978/77891205-e90bf500-7270-11ea-99cf-f070e6f54566.gif)

Crash Stack:

```
 Process: net.programmierecke.radiodroid2, PID: 5430
 java.lang.RuntimeException: Failure delivering result ResultInfo{who=@android:requestPermissions:, request=1, result=-1, data=Intent { act=android.content.pm.action.REQUEST_PERMISSIONS (has extras) }} to activity {net.programmierecke.radiodroid2/net.programmierecke.radiodroid2.ActivityMain}: java.lang.IllegalStateException: Can not perform this action after onSaveInstanceState
 	at android.app.ActivityThread.deliverResults(ActivityThread.java:3699)
 	at android.app.ActivityThread.handleSendResult(ActivityThread.java:3742)
 	at android.app.ActivityThread.-wrap16(ActivityThread.java)
 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1393)
 	at android.os.Handler.dispatchMessage(Handler.java:102)
 	at android.os.Looper.loop(Looper.java:148)
 	at android.app.ActivityThread.main(ActivityThread.java:5417)
 	at java.lang.reflect.Method.invoke(Native Method)
 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
 Caused by: java.lang.IllegalStateException: Can not perform this action after onSaveInstanceState
 	at androidx.fragment.app.FragmentManager.checkStateLoss(FragmentManager.java:1689)
 	at androidx.fragment.app.FragmentManager.enqueueAction(FragmentManager.java:1729)
 	at androidx.fragment.app.BackStackRecord.commitInternal(BackStackRecord.java:321)
 	at androidx.fragment.app.BackStackRecord.commit(BackStackRecord.java:286)
 	at androidx.fragment.app.DialogFragment.show(DialogFragment.java:175)
 	at net.programmierecke.radiodroid2.ActivityMain.SaveFavourites(ActivityMain.java:706)
 	at net.programmierecke.radiodroid2.ActivityMain.onRequestPermissionsResult(ActivityMain.java:449)
 	at android.app.Activity.dispatchRequestPermissionsResult(Activity.java:6553)
 	at android.app.Activity.dispatchActivityResult(Activity.java:6432)
 	at android.app.ActivityThread.deliverResults(ActivityThread.java:3695)
 	... 9 more
```

**Comment by Wikinaut** [comment]
See #612.

The problem is still present on some of my older devices, as described. It is apparently a problem when then permissions are not (yet) given to write the playlist to the memory.

**Comment by tingsu** [comment]
Yes, I saw this issue #612, which however did not lead to crash. You are right. It is related to the permission granting. From the issue message, I can tell it is related to lifecycle issue of Fragment (The fragement state is already saved, but the code intends to commit more changes). Before, I also analyzed a lot issues like this. Hope my input will be useful. Thanks.

**Comment by tingsu** [comment]
Any plan to fix this issue, thanks ?

**Comment by werman** [comment]
I was not able easily reproduce the crash in emulator. Does it happen every time you try?

**Comment by tingsu** [comment]
Hi @werman ,

Yes, for me, I can reproduce this crash very deterministically.

My emulator configuration is:

```
Device: Nexus 7 (Google)
Target: Google APIs (Google Inc.)
Based on: Android 6.0 (Marshmallow) Tag/ABI: google_apis/x86
Skin: 800x1280
Sdcard: 512 MB
Memory: 1536 MB
VM heapsize: 256 MB
```
I used this command line to create this avd: 
```
avdmanager create avd --force --name testAVD_Android6.0 --package 'system-images;android-23;google_apis;x86' --abi google_apis/x86 --sdcard 512M --device 'Nexus 7'
```

Let me know if you need more info.

**Comment by werman** [comment]
Ok, I'll try later with your config

**Comment by tingsu** [comment]
any update on this issue?

**Comment by werman** [comment]
Sorry, I haven't tested this yet.
