### ISSUE TITLE
Fatal crash - RuntimeException: Init failed

### ISSUE THREAD

**Issue by tingsu** [segler-alex/RadioDroid#779]
This crash issue was found in the latest released version (0.82) on an Android emulator 6.0. 

Statck trace

```
 FATAL EXCEPTION: main
 Process: net.programmierecke.radiodroid2, PID: 3536
 java.lang.RuntimeException: Init failed
 	at android.media.ToneGenerator.native_setup(Native Method)
 	at android.media.ToneGenerator.<init>(ToneGenerator.java:746)
 	at net.programmierecke.radiodroid2.service.PlayerService.lambda$warnAboutMeteredConnection$2$PlayerService(PlayerService.java:1086)
 	at net.programmierecke.radiodroid2.service.-$$Lambda$PlayerService$DzCXb4ZyKlcDNdjcK1hZBO2nKvo.run(lambda)
 	at android.os.Handler.handleCallback(Handler.java:739)
 	at android.os.Handler.dispatchMessage(Handler.java:95)
 	at android.os.Looper.loop(Looper.java:148)
 	at android.app.ActivityThread.main(ActivityThread.java:5417)
 	at java.lang.reflect.Method.invoke(Native Method)
 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

Let me know if you need more info from my end.

**Comment by werman** [comment]
What are the steps to reproduce?
