### ISSUE TITLE
Fatal crash - NullPointerException, Attempt to invoke interface method 'int java.util.List.size()' on a null object reference

### ISSUE THREAD

**Issue by tingsu** [segler-alex/RadioDroid#780]
This crash issue was found in the latest released version (0.82) on an Android emulator 6.0. 

Statck trace

```
Process: net.programmierecke.radiodroid2, PID: 19752
 java.lang.NullPointerException: Attempt to invoke interface method 'int java.util.List.size()' on a null object reference
 	at net.programmierecke.radiodroid2.station.ItemAdapterStation.notifyChangedByStationUuid(ItemAdapterStation.java:553)
 	at net.programmierecke.radiodroid2.station.ItemAdapterStation.access$200(ItemAdapterStation.java:43)
 	at net.programmierecke.radiodroid2.station.ItemAdapterStation$2.onReceive(ItemAdapterStation.java:183)
 	at androidx.localbroadcastmanager.content.LocalBroadcastManager.executePendingBroadcasts(LocalBroadcastManager.java:313)
 	at androidx.localbroadcastmanager.content.LocalBroadcastManager$1.handleMessage(LocalBroadcastManager.java:121)
 	at android.os.Handler.dispatchMessage(Handler.java:102)
 	at android.os.Looper.loop(Looper.java:148)
 	at android.app.ActivityThread.main(ActivityThread.java:5417)
 	at java.lang.reflect.Method.invoke(Native Method)
 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

Let me know if you need more info from my end.

**Comment by werman** [comment]
What are the steps to reproduce?
